# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec4870dba5550af5a797613e836e17b6600ca9184fb406d5b772b01d8ad0072d22e6bd574619cd4761b0e8b376cc7d822112ff106177586a559c771d76afb671

test:
  secret_key_base: 7e125ca3248074fe27786c910eeb4bd400c3044f2d5826453194a1a01a78e53fe382dd8e33b6554ccda488dcf7145dd2f88d3c550fc6f88b3ec7989310f2d0c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
